envio desafio 2
mellyssaStephanny/onboarding_environment pull request #2
Opened 2021-12-13 17:18 UTC by mellyssaStephanny

2021-12-13 19:43 UTC, ArthurFreitas requested changes

2021-12-13 19:43 UTC, ArthurFreitas commented on phoenix/app/apiProducts/lib/apiProducts_web/router.ex
> +  scope "/api", ApiProductsWeb do
Precisa usar a mesma rota do desafio 1.

2021-12-13 19:43 UTC, ArthurFreitas commented on phoenix/app/apiProducts/config/dev.exs
> +  database: "apiproducts_dev",
Usar o mesmo banco do primeiro desafio: "my_products_development"

2021-12-13 19:43 UTC, ArthurFreitas commented on phoenix/app/apiProducts/lib/apiProducts/catalog/product.ex
> +    field :amount,      :integer
No desafio1 é `qtd`

2021-12-13 19:43 UTC, ArthurFreitas commented on phoenix/app/apiProducts/lib/apiProducts_web/views/product_view.ex
> +    %{data: render_many(products, ProductView, "product.json")}
No desafio1 ficou "products" como chave

2021-12-13 19:43 UTC, ArthurFreitas commented on phoenix/app/apiProducts/lib/apiProducts_web/views/product_view.ex
> +    %{data: render_one(product, ProductView, "product.json")}
No desafio1 ficou sem chave

2021-12-13 19:43 UTC, ArthurFreitas commented on phoenix/app/apiProducts/lib/apiProducts_web/controllers/product_controller.ex
> +    product = Catalog.get_product!(id)
Precisa tratar o caso de não encontrar o produto, atualmente está retornando o stacktrace do erro `Ecto.NoResultsError`. Tu pode usar a versão que não levanta erro ao não encontrar https://hexdocs.pm/ecto/Ecto.Repo.html#c:get/3

2021-12-13 19:43 UTC, ArthurFreitas commented on phoenix/app/apiProducts/lib/apiProducts_web/controllers/product_controller.ex
> +    product = Catalog.get_product!(id)
E tratar o novo retorno no fallback controller

2021-12-13 19:43 UTC, ArthurFreitas commented on phoenix/app/apiProducts/lib/apiProducts_web/controllers/product_controller.ex
> +      |> put_resp_header("location", Routes.product_path(conn, :show, product))
Por ser uma API, não precisa dar replace no location pro /show aqui

2021-12-13 19:43 UTC, ArthurFreitas commented on phoenix/app/apiProducts/lib/apiProducts_web/controllers/product_controller.ex
> +    product = Catalog.get_product!(id)
Precisa tratar no update/delete também

2021-12-13 19:43 UTC, ArthurFreitas commented on phoenix/app/apiProducts/lib/apiProducts_web/views/changeset_view.ex
> +    %{errors: translate_errors(changeset)}
É bom entender direitinho como chega aqui a partir de um erro

2021-12-13 19:43 UTC, ArthurFreitas commented on phoenix/app/apiProducts/lib/apiProducts_web/controllers/product_controller.ex
> +    with {:ok, %Product{} = product} <- Catalog.create_product(product_params) do
O credo costumava reclamar de with com um único generator, se possível adiciona outro ou substitua para um case nos casos que ocorre.

2021-12-13 19:53 UTC, ArthurFreitas commented on phoenix/app/apiProducts/lib/apiProducts_web/controllers/product_controller.ex
> +    product = Catalog.get_product!(id)
Para evitar repetir essa linha tu pode utilizar um plug, funciona parecido ao before_action do rails, nas rotas que precisam buscar o product pelo id. https://elixirschool.com/pt/lessons/misc/plug

2021-12-14 20:57 UTC, NoahCamargo requested changes

2021-12-14 20:57 UTC, NoahCamargo commented on phoenix/app/apiProducts/lib/apiProducts_web/controllers/product_controller.ex
> +
Remover espaço

2021-12-14 20:57 UTC, NoahCamargo commented on phoenix/app/apiProducts/lib/apiProducts_web/controllers/product_controller.ex
> +
Segundo o style guide, não temos esses dois espaços https://github.com/christopheradams/elixir_style_guide

2021-12-14 20:57 UTC, NoahCamargo commented on phoenix/app/apiProducts/lib/apiProducts_web/controllers/product_controller.ex
> +    product = Catalog.get_product!(id)
Como terá que fazer nos dois casos, é conveniente usar o `plug`, que é semelhante ao `before_action` do Rails

2021-12-15 19:13 UTC, ArthurFreitas commented on phoenix/app/apiProducts/lib/apiProducts/catalog.ex
> +  def change_product(%Product{} = product, attrs \\ %{}) do
Essa função não é chamada por ninguem, pode remover.

2021-12-15 19:13 UTC, ArthurFreitas commented on phoenix/app/apiProducts/lib/apiProducts_web/controllers/product_controller.ex
> +      _ -> "Condition were not satisfied"
Aqui tu pode só retornar:
`error -> error`
por essa action não ter tido nenhuma resposta(em caso de erro) vai cair no `FallbackController.call(conn, {:error, %Ecto.Changeset{})` que vai renderizar a resposta explicando os erros direitinho para o cliente.

2021-12-15 19:13 UTC, ArthurFreitas commented on phoenix/app/apiProducts/lib/apiProducts_web/controllers/product_controller.ex
> +  defp find_product(conn, _opts) do
Pode remover essa função e usar o plug com PlugId modificado.

2021-12-15 19:13 UTC, ArthurFreitas commented on phoenix/app/apiProducts/lib/apiProducts_web/controllers/product_controller.ex
> +  plug :find_product when action in [:show, :update, :delete]
Para usar o módulo que tu criou para o plug no lugar da função:

`plug ApiProductsWeb.Plugs.PlugId when action in [:show, :update, :delete]`

2021-12-15 19:13 UTC, ArthurFreitas commented on phoenix/app/apiProducts/lib/apiProducts_web/plugs/plug_id.ex
> +defmodule ApiProductsWeb.Plugs.PlugId do
Para usar o plug certinho, tu precisa definir as funções de `call` e `init`, dá uma lida aqui: https://hexdocs.pm/plug/Plug.html

Ficaria algo assim:
```
defmodule ApiProductsWeb.Plugs.PlugId do
  import Plug.Conn

  alias ApiProducts.Catalog

  def init(opts), do: opts

  def call(conn, _opts) do
    id = conn.params["id"]
    product = Catalog.get_product(id)
    if product do
      assign(conn, :product, product)
    else
      conn
      |> send_resp(404, "")
      |> halt()
    end
  end
end
```

2021-12-15 19:13 UTC, ArthurFreitas commented on phoenix/app/apiProducts/lib/apiProducts_web/plugs/plug_id.ex
> +      send_resp(conn, 404, "Product not found")
Aqui faltou dar halt na conn, para evitar de enviar duas respostas para o mesmo request que causa o erro:
(Plug.Conn.AlreadySentError) the response was already sent.

2021-12-15 19:13 UTC, ArthurFreitas commented on phoenix/app/apiProducts/lib/apiProducts_web/controllers/fallback_controller.ex
> +  def call(conn, {:error, :not_found}) do
Pode remover esse match, agora que o plugId cuida da resposta.

2021-12-15 19:13 UTC, ArthurFreitas commented on phoenix/app/apiProducts/lib/apiProducts_web/controllers/fallback_controller.ex
> +  def call(conn, {:error, :bad_request}) do
Acho que esse match nunca é feito com teu código atual, pode remover.

2021-12-15 19:13 UTC, ArthurFreitas commented on phoenix/app/apiProducts/lib/apiProducts_web/router.ex
> +      resources "/products", ProductController, except: [:new, :edit]
Pode remover essa rota aqui

2021-12-15 23:15 UTC, ArthurFreitas approved these changes

2021-12-16 13:20 UTC, merged