Recall desafio3
mellyssaStephanny/onboarding_environment pull request #4
Opened 2022-01-05 19:38 UTC by mellyssaStephanny

2022-01-05 20:13 UTC, phrodrigues commented on phoenix/app/apiProducts/lib/apiProducts_web/services/product.ex
> +        Cache.delete("product")
Qual a função dessa linha?

2022-01-11 15:23 UTC, NoahCamargo requested changes

2022-01-11 15:23 UTC, NoahCamargo commented on phoenix/app/apiProducts/lib/apiProducts_web/plugs/plug_cache_id.ex
> +
Remover espaço e adicionar entre o import e os alias

```
defmodule ApiProductsWeb.Plugs.PlugCacheId do
  import Plug.Conn

  alias ApiProducts.Cache
  alias ApiProducts.Catalog
```

2022-01-11 15:23 UTC, NoahCamargo commented on phoenix/app/apiProducts/lib/apiProducts_web/plugs/plug_cache_id.ex
> +        |> Plug.Conn.halt()
Como voce já deu um import no Plug.Conn, o halt() pode ser chamado diretamente

2022-01-11 15:23 UTC, NoahCamargo commented on phoenix/app/apiProducts/lib/apiProducts_web/plugs/plug_cache_id.ex
> +  end
O plug se chama "CacheId", mas onde esta o cache?

2022-01-11 15:23 UTC, NoahCamargo commented on phoenix/app/apiProducts/lib/apiProducts_web/plugs/plug_show_product.ex
> +  alias ApiProducts.Catalog.Product
Mesma formatação do outro plug

2022-01-11 15:23 UTC, NoahCamargo commented on phoenix/app/apiProducts/lib/apiProducts_web/plugs/plug_show_product.ex
> +
Remover espaço. No inicio e no fim do modulo não existe espaço extra

2022-01-11 15:23 UTC, NoahCamargo commented on phoenix/app/apiProducts/lib/apiProducts_web/plugs/plug_show_product.ex
> +        |> put_status(417)
Acredito que o mais indicado seja o 400. O 417 é mais para headers e pouco utilizado

2022-01-11 15:23 UTC, NoahCamargo commented on phoenix/app/apiProducts/lib/apiProducts_web/plugs/plug_show_product.ex
> +defmodule ApiProductsWeb.Plugs.PlugShowProduct do
Talvez PlugProductParams, fique melhor, pelo que ele faz

2022-01-11 15:23 UTC, NoahCamargo commented on phoenix/app/apiProducts/lib/apiProducts_web/controllers/product_controller.ex
>    alias ApiProducts.Catalog.Product
Como esse cara tem o mesmo da linha posterior, ele não esta sendo usado para nada. Se voce realmente quisesse usa-lo, poderia utilizar um "as", para renomeá-lo

2022-01-11 15:23 UTC, NoahCamargo commented on phoenix/app/apiProducts/lib/apiProducts_web/services/product.ex
> +    case ProductIndex.search_product(product) do
Acredito que ProductIndex não exista.

2022-01-11 15:23 UTC, NoahCamargo commented on phoenix/app/apiProducts/lib/apiProducts_web/services/product.ex
> +    ProductIndex.search_product(product)
Esta extra aqui

2022-01-11 15:23 UTC, NoahCamargo commented on phoenix/app/apiProducts/lib/apiProducts/index_product.ex
> +    query = Enum.map_join(params, "*&", fn {k, v} -> "#{k}:#{v}" end)
Caça com que se tiver dois filtro ("sku=1&name=test"), sejam complementados como um AND

2022-01-11 15:23 UTC, NoahCamargo commented on phoenix/app/apiProducts/lib/apiProducts/index_product.ex
> +  defp format_response(any), do: {:error, any}
Como esse match casa com qualquer coisa, sempre vai retornar `{:error, any}`

2022-01-11 15:23 UTC, NoahCamargo commented on phoenix/app/apiProducts/lib/apiProducts/index_product.ex
> +  defp format_response_id({:ok, 200, %{:hits => %{:hits => hist_list}}}),
Não é utilizado

2022-01-11 15:23 UTC, NoahCamargo commented on phoenix/app/apiProducts/lib/apiProducts_web/services/product.ex
> +      {:mongodb, products} -> products
Assumindo que ProductIndex seja IndexProduct, você não tem nenhum desses matchs

2022-01-11 15:23 UTC, NoahCamargo commented on phoenix/app/apiProducts/lib/apiProducts_web/controllers/product_controller.ex
>        error -> error
Seu fallback nao tem nenhum match de erro mais generico, então nada casaria se cair `{:error, "Erro do mal"}`

2022-01-11 15:23 UTC, NoahCamargo commented on phoenix/app/apiProducts/lib/apiProducts_web/services/product.ex
> +  def create(product) when is_map(product) do
Se não for map pode é para quebrar, mesmo?

2022-01-11 15:23 UTC, NoahCamargo commented on phoenix/app/apiProducts/lib/apiProducts_web/services/product.ex
> +    case Catalog.product_index(product) do
Catalog não tem `product_index`, esse metodo aparentemente esta em `product_index`

2022-01-13 11:45 UTC, NoahCamargo requested changes

2022-01-13 11:45 UTC, NoahCamargo commented on phoenix/app/apiProducts/lib/apiProducts_web/controllers/product_controller.ex
> +    {:ok, :no_content}
Se der erro durante a exclusão, mesmo assim ele retornaria sucesso

2022-01-13 11:45 UTC, NoahCamargo commented on phoenix/app/apiProducts/lib/apiProducts/index_product.ex
> +  def product_index(product) do
O padrão esta como search_product, delete_product, então aqui ficaria bom um update_product

2022-01-13 11:45 UTC, NoahCamargo commented on phoenix/app/apiProducts/lib/apiProducts_web/services/product.ex
> +    case IndexProduct.product_index(product) do
Ta faltando criar o produto no banco e ele esta sendo enviado para o elastic duas vezes

2022-01-13 11:45 UTC, NoahCamargo commented on phoenix/app/apiProducts/lib/apiProducts/index_product.ex
> +    query = Enum.map_join(params, "*&", fn{k, v} -> "#{k}:#{v}" end)
Faça um AND aqui. Se a pessoa passar um filtro como `name=teste&sku=123` e existir o name, mas não com esse sku, não é para retornar

2022-01-13 11:45 UTC, NoahCamargo commented on phoenix/app/apiProducts/lib/apiProducts/index_product.ex
> +  defp format_response(error), do: {:error, error}
Como esse match casa com qualquer coisa, sempre vai retornar `{:error, error}`. A ideia de fazer varias funções de mesma assinatura mas matchings diferentes é colocar os matchings mais restritivo antes, já que o programa ira executar sequencial, se logo na primeira condição ele casar, nem vai testar o resto

2022-01-13 11:45 UTC, NoahCamargo commented on phoenix/app/apiProducts/lib/apiProducts_web/plugs/plug_cache_id.ex
> +  end
O codigo no geral esta muito compacto, tente dar uns enters. Mas o interessante mesmo seria instalar um lint para formatar o código

```
  # plug for cache redis
  def get_cache(conn, _id) do
    id = conn.params["id"]

    case Cache.get(id) do
      {:ok, product} ->
        assign(conn, :product, product)

      _ ->
        case Catalog.get_product(id) do
          nil ->
            conn
            |> halt()
            |> send_resp(:not_found, "")

          product ->
            assign(conn, :product, product)
        end
    end
  end
```

Um formato mais interessante

2022-01-13 11:45 UTC, NoahCamargo commented on phoenix/app/apiProducts/lib/apiProducts_web/controllers/product_controller.ex
> +    Product.create(conn.assigns[:product_params])
:product_params aparentemente não esta sendo setado em lugar algum

2022-01-13 11:45 UTC, NoahCamargo commented on phoenix/app/apiProducts/lib/apiProducts_web/plugs/plug_cache_id.ex
> +          assign(conn, :product, product)
Achando o produto já da pra setar no cache

2022-01-13 11:45 UTC, NoahCamargo commented on phoenix/app/apiProducts/lib/apiProducts_web/controllers/product_controller.ex
> +    conn.assigns[:product]
Não tem um match para %Product{} no fallback

2022-01-14 11:36 UTC, NoahCamargo requested changes

2022-01-14 11:36 UTC, NoahCamargo commented on phoenix/app/apiProducts/lib/apiProducts_web/plugs/plug_cache_id.ex
> +        _ ->
Sem o product, vai dar erro nas linhas seguintes, pois ele não existira

2022-01-14 11:49 UTC, NoahCamargo requested changes

2022-01-14 11:49 UTC, NoahCamargo commented on phoenix/app/apiProducts/lib/apiProducts_web/controllers/fallback_controller.ex
> +  def call(conn, {%Product{} = product}) do
O que vem é só product, não?

2022-01-14 11:49 UTC, NoahCamargo commented on phoenix/app/apiProducts/lib/apiProducts_web/controllers/product_controller.ex
> +    Product.create(conn.assigns[:product_params])
Se reparar, product_params é uma variável e conn.assigns[:product_params], é um valor presente em uma estrutura, são coisas diferentes

2022-01-14 11:49 UTC, NoahCamargo commented on phoenix/app/apiProducts/lib/apiProducts_web/controllers/product_controller.ex
> +    Product.fetch_all(conn.assigns[:product_params])
:product_params não é atribuido em lugar algum

2022-01-14 11:49 UTC, NoahCamargo commented on phoenix/app/apiProducts/lib/apiProducts/index_product.ex
>    defp format_response({:ok, 200}), do: {:ok, []}
Falta um retorno que seja :ok e não seja vazio

2022-01-14 13:19 UTC, NoahCamargo requested changes

2022-01-14 13:19 UTC, NoahCamargo commented on phoenix/app/apiProducts/lib/apiProducts_web/controllers/product_controller.ex
> +    end
Não é assim que se usa o case

2022-01-14 13:19 UTC, NoahCamargo commented on phoenix/app/apiProducts/lib/apiProducts_web/controllers/product_controller.ex
> +      render(conn.assigns[:product_params])
Tambem não é assim que se usa ele. Faltou o end tambem

2022-01-14 13:21 UTC, NoahCamargo requested changes

2022-01-14 13:21 UTC, NoahCamargo commented on phoenix/app/apiProducts/lib/apiProducts_web/controllers/fallback_controller.ex
> +  def call(conn, product) do
Isso vai casar qualquer coisa

2022-01-14 13:21 UTC, NoahCamargo commented on phoenix/app/apiProducts/lib/apiProducts_web/controllers/product_controller.ex
> +  def index(conn, "product" => product_params) do
Maps precisam do `%{}`

2022-01-14 13:21 UTC, NoahCamargo commented on phoenix/app/apiProducts/lib/apiProducts/index_product.ex
> +  defp format_response({:ok, error}), do: {:ok, error}
melhor result do que erro, já que é o caminho feliz

2022-01-18 11:51 UTC, NoahCamargo requested changes

2022-01-18 11:51 UTC, NoahCamargo commented on phoenix/app/apiProducts/lib/apiProducts/index_product.ex
> +    query = Enum.map_join(params, "%20AND%20", fn {k, v} -> "#{k}:#{v}" end)
Da um espaço entre essa linha e a proxima

2022-01-18 11:51 UTC, NoahCamargo commented on phoenix/app/apiProducts/lib/apiProducts/index_product.ex
> +  defp format_response({:ok, 200, %{hits: %{hits: hits}}}), do: {:ok, hits}
Faltou acessar o _source

2022-01-18 11:51 UTC, NoahCamargo commented on phoenix/app/apiProducts/lib/apiProducts/index_product.ex
> +  defp format_response({:ok, result}), do: {:ok, result}
Esse seria o caso de erro não?

2022-01-18 11:51 UTC, NoahCamargo commented on phoenix/app/apiProducts/lib/apiProducts_web/controllers/fallback_controller.ex
> +    render(conn, :no_content, "")
Não existe view que case com isso

2022-01-18 11:51 UTC, NoahCamargo commented on phoenix/app/apiProducts/lib/apiProducts_web/controllers/product_controller.ex
> +    end
E esse do, end?

2022-01-18 11:51 UTC, NoahCamargo commented on phoenix/app/apiProducts/lib/apiProducts_web/controllers/product_controller.ex
> +    {:error, "Could not create product"}
Acho que ficaria melhor a mensagem se ela disse o que tem de errado com o payload

2022-01-18 11:51 UTC, NoahCamargo commented on phoenix/app/apiProducts/lib/apiProducts_web/plugs/plug_id.ex
> +  end
Esse plug parece que não esta sendo utilizado para nada, daria para remover

2022-01-18 11:51 UTC, NoahCamargo commented on phoenix/app/apiProducts/lib/apiProducts_web/services/product.ex
Remover espaço

2022-01-18 11:51 UTC, NoahCamargo commented on phoenix/app/apiProducts/lib/apiProducts_web/services/product.ex
> +        {:ok, :no_content}
Adicione um enter entre o IndexProduct e esse retorno

2022-01-18 14:01 UTC, NoahCamargo requested changes

2022-01-18 14:01 UTC, NoahCamargo commented on phoenix/app/apiProducts/lib/apiProducts_web/services/product.ex
> +        {:ok, :no_content}
No caso seria a aqui

```
        IndexProduct.delete_product(product)
        
        {:ok, :no_content}
```

2022-01-18 18:05 UTC, NoahCamargo approved these changes

2022-01-18 19:24 UTC, merged